---
- import_tasks: install.yml
- import_tasks: config.yml
- import_tasks: cron.yml
- import_tasks: verify.yml


# ---
# # tasks file for service
# - name: Install nginx
#   apt: 
#     name: nginx
#     state: present

# - name: Install cron
#   apt:
#     name: cron
#     state: present

# - name: Install jq
#   apt:
#     name: jq
#     state: present

# - name: create file json from template
#   template:
#     src: service_state.json.j2
#     dest: /opt/service_state.json
#   notify: restart nginx

# - name: Ensure nginx is running
#   service:
#     name: nginx
#     state: started

# - name: Ensure cron is running
#   service:
#     name: cron
#     state: started
#     enabled: yes

# - name: Add nginx config file
#   template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/conf.d/service.conf
#   notify: restart nginx

# - name: Add cmd to cron
#   cron:
#     name: "update_nginx_uptime"
#     minute: "*"
#     job: 'UP=$(($(ps -o etimes= -p $(cat /var/run/nginx.pid)) / 60)); jq ".uptime = $UP" /opt/service_state.json > /opt/service_state.tmp.json && mv /opt/service_state.tmp.json /opt/service_state.json'

# - name: Get before uptime
#   command: jq -r '.uptime' /opt/service_state.json
#   register: uptime_before

# - debug:
#     msg: "Uptime old = {{ uptime_before.stdout }}"

# - pause:
#     seconds: 70

# - debug:
#     msg: "Wait for 70 seconds"

# - name: Get after uptime
#   command: jq -r '.uptime' /opt/service_state.json
#   register: uptime_after

# - debug:
#     msg: "Uptime new = {{ uptime_after.stdout }}"
  
# - assert:
#     that:
#     - uptime_after.stdout | int > uptime_before.stdout | int